const ONE_SECOND = 1000;

const ONE_MINUTE = 60 * ONE_SECOND;
const FIVE_MINUTES = 5 * ONE_MINUTE;
const TEN_MINUTES = 5 * ONE_MINUTE;

const ONE_HOUR = 60 * ONE_MINUTE;

const ONE_DAY = 24 * ONE_HOUR;

const MILLISECONDS = {
	 ONE_SECOND,
	 ONE_MINUTE,
	 FIVE_MINUTES,
	 TEN_MINUTES,
	 ONE_HOUR,
	 ONE_DAY,
}

exports.MILLISECONDS = MILLISECONDS;